# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PyConf Hyderabad 2019
mail: contact@hydpy.org
description: >- # this means to ignore newlines until "baseurl:"
  PyConf Hyderabad is an yearly tech conference about python, it's projects and development
keywords: "PyConf, python, 2019, Hyderabad, pyconf hyderabad 2019, data science, machine learning, conference, tech conference"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pyconf.hydpy.org/2019/" # the base hostname & protocol for your site, e.g. http://example.com

twitter: https://twitter.com/pyconfhyd
github:  https://github.com/hydpy

# links
tickets_link: "#tickets-section"
schedule_link: ""
cfp_link: "https://www.papercall.io/pyconf-hyderabad2019"
social_image_link: "https://pyconf.hydpy.org/2019/assets/images/pyconflogo_ai_compressed.jpg"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "https://www.iiit.ac.in/"
eventStreetAddress: "IIIT Hyderabad"
eventAddressLocality: "Hyderabad"
eventAddressLocalityRegion: "Telangana"
eventPostalCode: "500032"
eventAddressCountry: "India"
eventStartTime: "2017-10-07T09:30"
eventDoorTime: "09:00"
eventEndTime: "2017-10-08T17:00"
eventPlaceCoordinates: "17.4455415, 78.3471251"
mapCenterCoordinates: "17.4455415, 78.3471251"
mapMobileCenterCoordinates: "17.4455415, 78.3471251"

sass:
  sass_dir: _sass
  style: compressed

# jekyll-compress-html
compress_html:
  clippings: all
  comments: [""]
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - deploy.sh
